# Generated by Django 3.0.7 on 2020-06-15 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import q4back.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('information', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('artist_website', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_palette', models.CharField(choices=[('mixed', 'mixed'), ('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green'), ('purple', 'purple'), ('orange', 'orange'), ('brown', 'brown'), ('black', 'black'), ('white', 'white'), ('grey', 'grey')], default='mixed', max_length=6)),
                ('secondary_palette', models.CharField(choices=[('mixed', 'mixed'), ('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green'), ('purple', 'purple'), ('orange', 'orange'), ('brown', 'brown'), ('black', 'black'), ('white', 'white'), ('grey', 'grey')], default='mixed', max_length=6)),
                ('medium', models.CharField(choices=[('mixed', 'mixed'), ('music', 'music'), ('garment', 'garment'), ('painting', 'painting'), ('sculpture', 'sculpture'), ('photo', 'photo'), ('writing', 'writing'), ('drawing', 'drawing'), ('graphic', 'graphic'), ('website', 'website')], default='mixed', max_length=9)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='q4back.Artist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('unspecified', 'unspecified'), ('image', 'image'), ('audio', 'audio'), ('video', 'video'), ('document', 'document')], default='unspecified', max_length=11)),
                ('media_url', models.ImageField(upload_to=q4back.models.upload_media)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='q4back.Artwork')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('unspecified', 'unspecified'), ('image', 'image'), ('audio', 'audio'), ('video', 'video'), ('document', 'document')], default='unspecified', max_length=11)),
                ('media_url', models.ImageField(upload_to=q4back.models.upload_media)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='q4back.Artist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
