# Generated by Django 3.0.7 on 2020-06-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q4back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_media',
        ),
    ]
