# Generated by Django 3.0.7 on 2020-06-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q4back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmedia',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='q4back.Artist'),
            preserve_default=False,
        ),
    ]
