# Generated by Django 3.0.7 on 2020-06-10 17:37

from django.db import migrations, models
import q4back.models


class Migration(migrations.Migration):

    dependencies = [
        ('q4back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ArtworkMedia',
            name='image_url',
            field=models.ImageField(
                blank=True, upload_to=q4back.models.upload_image),
        ),
    ]
