# Generated by Django 3.0.7 on 2020-06-12 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q4back', '0002_remove_artwork_artwork_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artwork_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artwork_media', to='q4back.ArtworkMedia'),
        ),
    ]
