# Generated by Django 3.0.7 on 2020-06-11 18:28

from django.db import migrations, models
import q4back.models


class Migration(migrations.Migration):

    dependencies = [
        ('q4back', '0002_auto_20200611_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkmedia',
            name='media_url',
            field=models.ImageField(blank=True, null=True, upload_to=q4back.models.upload_media),
        ),
    ]
