# Generated by Django 3.0.7 on 2020-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q4back', '0002_artistmedia_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmedia',
            name='file_type',
            field=models.CharField(choices=[('unspecified', 'unspecified'), ('image', 'image'), ('audio', 'audio'), ('video', 'video'), ('document', 'document')], default='unspecified', max_length=11),
        ),
        migrations.AddField(
            model_name='artworkmedia',
            name='file_type',
            field=models.CharField(choices=[('unspecified', 'unspecified'), ('image', 'image'), ('audio', 'audio'), ('video', 'video'), ('document', 'document')], default='unspecified', max_length=11),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(choices=[('mixed', 'mixed'), ('music', 'music'), ('garment', 'garment'), ('painting', 'painting'), ('sculpture', 'sculpture'), ('photo', 'photo'), ('writing', 'writing'), ('drawing', 'drawing'), ('graphic', 'graphic'), ('website', 'website')], default='mixed', max_length=9),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='primary_palette',
            field=models.CharField(choices=[('mixed', 'mixed'), ('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green'), ('purple', 'purple'), ('orange', 'orange'), ('brown', 'brown'), ('black', 'black'), ('white', 'white'), ('grey', 'grey')], default='mixed', max_length=6),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='secondary_palette',
            field=models.CharField(choices=[('mixed', 'mixed'), ('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green'), ('purple', 'purple'), ('orange', 'orange'), ('brown', 'brown'), ('black', 'black'), ('white', 'white'), ('grey', 'grey')], default='mixed', max_length=6),
        ),
    ]
