# Generated by Django 3.0.7 on 2020-06-10 17:43

from django.db import migrations, models
import q4back.models


class Migration(migrations.Migration):

    dependencies = [
        ('q4back', '0002_auto_20200610_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=q4back.models.upload_image),
        ),
    ]
