# Generated by Django 3.0.7 on 2020-06-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q4back', '0003_auto_20200611_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_media', to='q4back.ArtistMedia'),
        ),
    ]
