# Generated by Django 3.0.7 on 2020-06-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q4back', '0003_artwork_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image_url',
        ),
    ]
