# Generated by Django 3.0.7 on 2020-06-11 21:04

from django.db import migrations, models
import django.db.models.deletion
import q4back.models


class Migration(migrations.Migration):

    dependencies = [
        ('q4back', '0004_auto_20200611_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_media',
            field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, related_name='artist_media', to='q4back.ArtistMedia'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_website',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artistmedia',
            name='media_url',
            field=models.ImageField(default='DEFAULT VALUE', upload_to=q4back.models.upload_media),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(choices=[('none', 'none'), ('sculpture', 'sculpture'), ('flat art', 'flat art'), ('audio', 'audio')], default='none', max_length=9),
        ),
        migrations.AlterField(
            model_name='artworkmedia',
            name='media_url',
            field=models.ImageField(default='DEFAULT VALUE', upload_to=q4back.models.upload_media),
        ),
    ]
