# Generated by Django 3.0.7 on 2020-06-15 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('q4back', '0004_auto_20200613_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistmedia',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='q4back.Artist'),
        ),
        migrations.AlterField(
            model_name='artistmedia',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
